code --install-extension 2gua.rainbow-brackets
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension esbenp.prettier-vscode
code --install-extension ExodiusStudios.comment-anchors
code --install-extension felixfbecker.php-intellisense
code --install-extension humao.rest-client
code --install-extension jeff-hykin.polacode-2019
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension shardulm94.trailing-spaces
